#version: "3.8"

services:
   postgres:
     image: postgres:16
     container_name: poke_api #this is to put en instead o the ip
     environment:
       - POSTGRES_DB=poke_api_db
       - POSTGRES_USER=juan
       - POSTGRES_PASSWORD=admin123
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # Using environment variable from .env file POSTGRES_PASSWORD=admin123
     ports:
       - '5434:5432'
     volumes:
#       - /postgres_data:/var/lib/postgresql/data # This is a bind mount, it maps a directory from the host to the container.
       - postgres_data:/var/lib/postgresql/data #volumen nombrado Ese volumen vive en el almacenamiento interno de Docker, no dentro de tu proyecto.


   pgadmin:
     image: dpage/pgadmin4
     environment:
       - PGADMIN_DEFAULT_EMAIL=juan@mail.com # mail, no gmail
       - PGADMIN_DEFAULT_PASSWORD=admin123
     ports:
       - 5050:80
     depends_on:
       - postgres
volumes:
  postgres_data:
  # Servicio de base de datos MySQL

#  mysql:
#    image: mysql:5.7
#    container_name: mysql_escolar
#    environment:
#      MYSQL_DATABASE: api_escolar
#      # MYSQL_USER: root # comentar o descomentar en caso de que no funcione mysql
#      MYSQL_PASSWORD: admin123
#      MYSQL_ROOT_PASSWORD: admin123
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#    networks:
#      - escolar_net
#
#  # Servicio phpMyAdmin
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    container_name: phpmyadmin_escolar
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      MYSQL_ROOT_PASSWORD: admin123
#    ports:
#      - "8081:80"
#    depends_on:
#      - mysql
#    networks:
#      - escolar_net
#
## Volúmenes persistentes
#volumes:
#  mysql_data:
#
## Red compartida entre servicios
#networks:
#  escolar_net:
#    driver: bridge